name: Daily ETL Job

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 5 AM UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  run_etl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ETL job
        run: python etl/job.py
